// AUTO-GENERATED by scripts/gen-brand-kit.cjs — DawnWire brand kit assets
// hosted on iili.io (freeimage.host). Regenerate after re-uploading.

export const BRAND_KIT = {
  heroes: [
    { desktop: 'https://iili.io/CZDYvmx.png', mobile: 'https://iili.io/CZD0XTb.png', href: '/categories/electronics', alt: 'Electronics deals — headphones, monitors, laptops & smart home' },
    { desktop: 'https://iili.io/CZDa5Tx.png', mobile: 'https://iili.io/CZD1lDJ.png', href: '/categories/gaming', alt: 'Gaming gear — keyboards, mice, headsets & accessories' },
    { desktop: 'https://iili.io/CZDatae.png', mobile: 'https://iili.io/CZDE7ql.png', href: '/categories/home-kitchen', alt: 'Home & kitchen essentials — cookware, coffee & appliances' },
    { desktop: 'https://iili.io/CZDY3xV.png', mobile: 'https://iili.io/CZDlB07.png', href: '/categories/beauty-personal-care', alt: 'Beauty & skincare — Korean skincare, serums & grooming' },
    { desktop: 'https://iili.io/CZDcTPI.png', mobile: 'https://iili.io/CZDGBQj.png', href: '/categories/office-productivity', alt: 'Office & productivity — desks, chairs & workspace gear' },
  ],
  sidePromos: [
    { src: 'https://iili.io/CZDxVWu.png', href: '/categories/electronics', alt: 'Electronic deals' },
    { src: 'https://iili.io/CZDomcQ.png', href: '/categories/beauty-personal-care', alt: 'Beauty & Grooming' },
    { src: 'https://iili.io/CZDxUWg.png', href: '/categories/home-kitchen', alt: 'Home & Kitchen' },
    { src: 'https://iili.io/CZDxzNt.png', href: '/products?sort=rating', alt: 'Best Sellers Top Rated' },
  ],
  trustIcons: {
    'Independently Reviewed': 'https://iili.io/CZDGNnf.th.png',
    'Live Price Checks': 'https://iili.io/CZDo8Pf.th.png',
    'Price History Tracking': 'https://iili.io/CZDGrue.th.png',
    'Amazon Verified Links': 'https://iili.io/CZDGVyX.th.png',
    'Expert Buying Guides': 'https://iili.io/CZDGjZG.th.png',
    'Secure Affiliate Links': 'https://iili.io/CZDGZFV.th.png',
  } as Record<string, string>,
  featureBanners: {
    aiFinder: { src: 'https://iili.io/CZDxL5N.png', href: '/compare' },
    priceDrop: { src: 'https://iili.io/CZDGE3N.png', href: '/deals' },
  },
  categoryStrips: {
    'beauty-personal-care': 'https://iili.io/CZD5jQS.png',
    'electronics': 'https://iili.io/CZD5L6F.png',
    'gaming': 'https://iili.io/CZD7dGt.png',
    'home-kitchen': 'https://iili.io/CZD7TP9.png',
    'office-productivity': 'https://iili.io/CZD7NNR.png',
  } as Record<string, string>,
};
